Removed redundancy issue (#77)
integritee-network/crowdloan pull request #84
Opened 2021-11-02 15:26 UTC by Alirazadar

2021-11-03 14:33 UTC, brenzi requested changes

2021-11-03 14:33 UTC, brenzi commented on src/SupporterReward.js
> +                                                        If Integritee doesn’t win an auction and the crowdloan ends
why is this still redundant?

2021-11-03 18:19 UTC, brenzi commented on src/SupporterReward.js
> +                                                        If Integritee doesn’t win an auction and the crowdloan ends
the same text appears twice in this file

2021-11-04 13:43 UTC, brenzi commented on src/SupporterReward.js
> +                                                        If Integritee doesn’t win an auction and the crowdloan ends
I'm totally wrong, sorry. not the same text. my bad

2021-11-04 13:44 UTC, brenzi commented
@mosonyi PR is fine for me, but I haven't tested. can you?

2021-11-04 13:55 UTC, Alirazadar commented on src/SupporterReward.js
> +                                                        If Integritee doesn’t win an auction and the crowdloan ends
@brenzi thank you for the clarification!

2021-12-09 09:17 UTC, anizeani commented
tested on mobile and it works. 
2 remarks: 
1. Couldn't test the contribution vis polkadot js extension, because it is not available for mobile, just for chrome & firefox on computer, right? Is there another way to test contribution via mobile or just not possible? (maybe add it as a 3rd hint after "ensure that you have unbounded KSM ...". Of course only if you think it's relevant
2. The hamburger button in the upper menu/navbar: when pressing it and then pressing on a topic, the hamburger window remains open until I repress the hamburger button. Is this the desired behaviour? Usually pressing a topic should close the hamburger window immediately..

2021-12-10 07:43 UTC, brenzi approved these changes

2021-12-15 07:20 UTC, brenzi commented
mobile is fine, but desktop not, grphic should not cover text and dots should be close to milestone text

2021-12-26 03:02 UTC, anizeani commented
Different screen sizes are shown here. 
1. The graphic never overlaps with the text (different screen sizes are shown. The developer tools in chrome are used to display the different screen resolutions (1920x1080, 1600x900, 1680x1050, 1300x768 and below 1200width (mobile--> folds text and removes background image)
2. The 2 dots are close to the text

An easy way to verify/test it is: 
on pc: yarn start --> in chrome open console and move the slider to make screen smaller or use the actual developer tools to set screen size / device size.
on real mobile: in the same wifi network go to the pc's ip adress:port running the react project
Example images:  
![below_1200px_width_without_image_(mobile_view)](https://user-images.githubusercontent.com/36300021/147397782-2eec1de0-e89c-4e69-b60c-dd9d8ea34587.png)
![1920_1080](https://user-images.githubusercontent.com/36300021/147397781-0a1d9224-683b-498f-9516-b93cf8ba5a37.png)
![1680_1050](https://user-images.githubusercontent.com/36300021/147397780-48436e20-91d2-4bdf-b0a4-907881781b35.png)
![1300_768](https://user-images.githubusercontent.com/36300021/147397776-8bd90b8a-8645-4f9c-b978-d62cab81d5ef.png)
![1600_900](https://user-images.githubusercontent.com/36300021/147397778-6eff5a02-e5ed-488a-a49b-7eb75fca82cc.png)

2022-01-03 08:15 UTC, brenzi approved these changes

2022-01-03 08:16 UTC, merged