changing finalized check to InBlock
integritee-network/crowdloan pull request #95
Opened 2021-12-07 22:40 UTC by anizeani

fixes #46

I'm not sure yet, but we can discuss it

2021-12-08 07:51 UTC, brenzi commented
I think we should offer a link to a block explorer, like:
https://kusama.subscan.io/extrinsic/0x13d401d96b7c87a9504d680d78e6de7aac7b6277875ac8dbee4fff62eea4b71b

2021-12-08 07:53 UTC, brenzi requested changes
LGTM, just insert link to subscan...

2021-12-08 08:54 UTC, anizeani commented
where do you want to have the link to subscan? 
after press of the participate button in the same window?

2021-12-08 09:25 UTC, brenzi commented
Where you show the tx hash to the user currently. just make that hash a link

2021-12-08 14:21 UTC, anizeani commented
I implemented the hyperlink to subscan, but subscan can't find the transaction. is it, because it will not get through?

2021-12-08 14:34 UTC, brenzi commented
subscan sometimes lags a little bit. have you tried a minute later?

2021-12-08 14:39 UTC, brenzi commented
here's the last. maybe add a note that users have to be patient and retry after a minute
https://kusama.subscan.io/extrinsic/0xd65752843160f79ebd0f83a5594a0f21653bf061e5699aeef2aa5da65ceed16e

2021-12-08 16:01 UTC, anizeani commented
my latest transactions: 
0xbb69a21d7ec40996007b3685c97e7aabf01f64cc56078886f460ac68ccae3093
0xce5141f4003b08039050958c3169bc6e9dda4cdfc8581529803158bf0e42fa55

I see that the contributions do happen, but the transaction hash I get is not the extrinsic hash shown in subscan

2021-12-09 08:09 UTC, anizeani commented
@brenzi, I solved it. We didn't actually output the transaction hash, but the block hash. Of course, the block hash doesn't (and will never) match the actual transaction hash.
I now get the signedBlock from the block hash and iterate over all its' extrinsics and I see, that it's the last entry: 
    
    const blockHash = status.asInBlock.toString();
    
    // returns SignedBlock
    const signedBlock = await api.rpc.chain.getBlock(hash);
    
    // the hash for each extrinsic in the block
    console.log(`"ALL EXTRINSICS OF BLOCK${signedBlock}`);
    signedBlock.block.extrinsics.forEach((ex, index) => {
      console.log(index, ex.hash.toHex());
    });

2021-12-09 08:23 UTC, anizeani commented
@brenzi, it's working for me now, please test. Also tell me, if you still want to see the block hash, or only the tx hash

2021-12-10 07:35 UTC, brenzi requested changes
now you do show the blockhash and the txhash with a link to subscan and it is a lot better from a UX perspective I think. However:
* When the use isn't fast enough, the status changes to "finalized" and the link to subscan is gone. Please also show the link and the blockhash when finalized
* Due to the horizontal scrolling it is not possible to select and copy-paste the blockhash or the tx hash. would be nice to have copy-paste buttons with both hashes for those who want to be sure to keep all info

2021-12-10 07:38 UTC, brenzi commented
moreover: with my first attempt, the extrinsic failed but it was finalized. is there a way how we can tell the user that the extrinsic has failed?
You can easily test this right now, because the last  few contributions have failed with `LiquidityRestrictions`
https://kusama.subscan.io/extrinsic/0x968fd206fcc6c6a401ed1fe05d49c87cebff988ecabea8c8fe28e4c20912d369

2021-12-10 07:40 UTC, brenzi commented
and please test ASAP, before we merge #97 as this will prevent the error from happening

2021-12-12 17:51 UTC, brenzi commented
the link to subscan is wrong

I send from the demo account EijCociWDFh6ZBKY3P6KnvujkmcttiNVrTLS8WvcQ7KDHRx

but the link points to another extrinsic by another address:

The crowdloan page shows me: 
link: https://kusama.subscan.io/extrinsic/0x15168b95a3f0ce3675d12464807a1b984daa1ab7003e56fd59dba74e0825bc97
tx hash: 0x15168b95a3f0ce3675d12464807a1b984daa1ab7003e56fd59dba74e0825bc97
block hash: 0xe0bb0d06afec6879c648b715ec8dd5c8e7ba6ca3a48668de1efc4b20f39e7c1b

should be: 
https://kusama.subscan.io/extrinsic/0x6aa8ac9d08011f62019849e57ac16ffb83082be98a76b36d35cd7ec46a126921

2021-12-12 17:54 UTC, brenzi requested changes

2021-12-12 17:54 UTC, brenzi commented on src/substrate-lib/components/TxButton.js
> +    const transactionHash = extrinsics[extrinsics.length - 1];
and this is the source of the error. why do you assume we're looking for the last extrinsic?

2021-12-15 22:44 UTC, anizeani commented on src/substrate-lib/components/TxButton.js
> +    const transactionHash = extrinsics[extrinsics.length - 1];
yes, you are right, and I was aware of that. Zoltan and I didn't know how to get the txHash when working with subscriptions, and this was infact MUCH HARDER to figure out then I guessed. 
So I tried just to take the last one, since the extrinsic just happened. When I tested it it never failed, but good that you had a wrong extrinsic hash, so we know this is no possible way to solve it. Good that we finally solved it^^

2021-12-21 07:43 UTC, brenzi approved these changes
works. copy-paste symbol is ugly indeed, but acceptable for now

2022-01-03 15:52 UTC, mosonyi reviewed
LGTM, except the mobile view.
![image](https://user-images.githubusercontent.com/6170620/147951268-406449e5-363a-4980-a25e-2ac2af85ce70.png)

2022-01-03 16:36 UTC, mosonyi commented
> LGTM, except the mobile view. ![image](https://user-images.githubusercontent.com/6170620/147951268-406449e5-363a-4980-a25e-2ac2af85ce70.png)

As cannot participate on mobile it is not so important.

2022-01-03 16:37 UTC, mosonyi approved these changes
Looks ok for me.

2022-01-03 18:56 UTC, merged

2022-01-03 18:58 UTC, brenzi commented on src/Participate.js
> +          const txExcecuteDummy = api.tx.crowdloan.contribute(paraId, data.value * Math.pow(10, 12), null);
mount doesn't matter for fees. I'll fix that separately

2022-01-03 21:18 UTC, anizeani commented on src/Participate.js
> +          const txExcecuteDummy = api.tx.crowdloan.contribute(paraId, data.value * Math.pow(10, 12), null);
I know it doesnt matter. Its just because it would also crash for negative numbers. But we can just put all the code in the try catch